apiVersion: v1
kind: Pod
metadata:
  name: fsgroup-test
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      emptyDir:
  terminationGracePeriodSeconds: 0
