apiVersion: v1
kind: Pod
metadata:
  name: sc-test
spec:
  containers:
  - image: memcached
    name: memcached
    securityContext:
      runAsUser: 11211
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - SYS_ADMIN
        - NET_ADMIN
