apiVersion: v1
kind: Pod
metadata:
  name: liveness-check
spec:
  containers:
    - name: nginx
      image: nginx
      livenessProbe:
        httpGet:
          port: 80
          path: /
        failureThreshold: 5
        periodSeconds: 5
